language: bash

branches:
  only:
    - master

script: 
  - bash dnsmasq.sh

deploy:
  provider: pages
  skip-cleanup: true
  github-token: ${GH_TOKEN}
  target-branch: gh-pages
  local-dir: rules
  keep-history: true
  on:
    branch: master
    repo: FenghenHome/filters
